### ISSUE TITLE
More flexible credentials picker

### ISSUE THREAD

**Issue by matuscak** [iSnackyCracky/KeePassRDP#15]
**Is your feature request related to a problem? Please describe.**
Currently, credentials picker functionality works only if server entry is located in specific, hard-coded location (path ending with **RDP** group) and credential entries are searched only in hard-coded path (parent of the RDP group). IMHO, this is too restrictive, it would be much more flexible if no specific layout will be enforced by the plugin.

**Describe the solution you'd like**
I recommend using custom string field as an alternative way to enable credential picker. We already support **rdpignore** field, similarly we could establish something like **rdpcppath**, which, if present, will enable credential picker and search for credential entries on the path specified as a field value. 

This should work on all server entries located anywhere, without RDP group requirement. Since the search path for the credentials will be user specified, it will deliver much more flexibility and will not enforce any specific layout.

Current behaviour should be kept for server entries in RDP group, for backward compatibility.

**Additional options**
If not too complicated, allowing to specify multiple credential paths would improve flexibility even more. 

You may also consider supporting additional, optional fields, like **rdpcpregex**.

**Comment by iSnackyCracky** [comment]
Hi @matuscak,

> I recommend using custom string field as an alternative way to enable credential picker. We already support rdpignore field, similarly we could establish something like rdpcppath, which, if present, will enable credential picker and search for credential entries on the path specified as a field value.

So you would like to specify a custom field per "server-entry" named (for example) "rdpcppath" and if this is present on an entry on which the plugin gets used it starts the credential-picker and searches the path specified in the value of this custom field, right?

I think this should be doable, probably with multiple paths in the value as well (separated by something like a semicolon or newline character)
As you said the RDP group functionality would stay for backwards compatibility (and some use cases, such as my personal, make more use of the current behavior, as I just have to create a new entry with a new server, and don't need to bother adding custom fields and parameters).
I would probably make your requested functionality additional to that. So that if an entry is located in the RDP group and has the custom field added, current behaviour applies and the search gets extended to also include the specified paths.

> You may also consider supporting additional, optional fields, like rdpcpregex.

So this would then be specific per "server-entry" just as the **rdpcppath**. Just in case u didn't already know, since [v1.12.0](https://github.com/iSnackyCracky/KeePassRDP/releases/tag/v1.12.0) it's already possible to (partly) edit the global regex used by the credpicker in the KeePassRDP options.


I hope I understood your request correctly, I think these are pretty cool enhancements I probably wouldn't ever thought about. Thank you very much for your suggestions and I'm looking forward to start implementing these in one of the next releases.

**Comment by matuscak** [comment]
Hi @iSnackyCracky, sorry for later answer, I was off for few days.

> So you would like to specify a custom field per "server-entry" named (for example) "rdpcppath" and if this is present on an entry on which the plugin gets used it starts the credential-picker and searches the path specified in the value of this custom field, right?

Yes, exactly, this is how I mean it.

> So this would then be specific per "server-entry" just as the rdpcppath. Just in case u didn't already know, since v1.12.0 it's already possible to (partly) edit the global regex used by the credpicker in the KeePassRDP options.

Yes, I know about global regex editing, thank you. But this could be server entry specific, what could be helpful if in different groups or database files naming is  done differently.


**For better understanding why I propose this enhancement:**
You could have AD domain with many servers and still use only few AD accounts for logging to them, e.g. one domain admin, your personal account and maybe few test user accounts with different privileges. In this scenario you have many server entries in Keepass and only few user account entries. Therefore it makes more sense to have all user entries in one group named for example  "AD users" and server entries organized in several groups,  e.g. per location or per AD organizational unit. 

My proposal allows implementing this (and many other) Keepass database organization scheme.

> I hope I understood your request correctly, I think these are pretty cool enhancements I probably wouldn't ever thought about. Thank you very much for your suggestions and I'm looking forward to start implementing these in one of the next releases.

It will be really great if you do it, thank you very much for your effort and all your work on this helpful extension!
