### ISSUE TITLE
Keyboard shortcut not working when KeeAgent is installed

### ISSUE THREAD

**Issue by massimobalestra** [iSnackyCracky/KeePassRDP#24]
**Describe the bug**
The keyboard shortcut (Ctrl+M) does not work with KeePass2.49.
It works if I right click on the entry and select "KeePassRDP"  --> "open RDP connection     Ctrl+M"
Ctrl+Alt+M works but, accordingly with the labels, it opens with /admin and I need to have a normal connection.

**To Reproduce**
1. select one entry 
2. type on the keyboard Ctrl+M
3. Nothing happens

If I select "KeePassRDP"--> "open RDP connection     Ctrl+M" it opens the RDP connection as expected.

**Expected behavior**
I would expect that after selecting the entry, Ctrl+M would open the RDP connection

**Comment by iSnackyCracky** [comment]
Hi @massimobalestra,

I've just tested the behavior on different machines with the new KeePass version 2.49.
For me it worked as expected so far.

If the shortcut doesn't work, but the context menu (or toolbar button) work just fine, it's probably due to some other application (or another KeePass Plugin) has registered the same keyboard shortcut earlier than the KeePassRDP plugin.
For example I've seen this exact behavior happen with the [KeeAgent plugin](https://lechnology.com/software/keeagent/), which uses the <kbd>CTRL</kbd>+<kbd>M</kbd> shortcut aswell and seems to get loaded into KeePass first (maybe plugins are loaded alphabetically).

You might also check the KeePass "Integration" options. Maybe there's a shortcut defined as <kbd>CTRL</kbd>+<kbd>M</kbd> for KeePass itself (although that wasn't the case for me).
![image](https://user-images.githubusercontent.com/20481463/133570875-f253d7ec-cf95-47c7-9010-36a60d9024ee.png)

**Comment by massimobalestra** [comment]
Hi @iSnackyCracky 
Thank you for the quick answer.
Yes, I have KeeAgent installed and I notice only now that, yes it has Ctrl+M mapped to something that it is not used (greyed out) for the rdp entry.
Is there a way to change the Keyboard shortcut mapping? I cannot find in KeePass any option to change it myself.
Thank you
(I change the subject to include the KeeAgent)

**Comment by iSnackyCracky** [comment]
Unfortunately, there is no such option for neither KeeAgent nor KeePassRDP (yet).
The shortcuts are registered "globally" when KeePass loads the plugin.
I had tried to implement some kind of customizable shortcut for KeePassRDP in the past, but wasn't really successful with it.
I still would like to implement this feature, but I don't know when this will happen.

Maybe until then the toolbar button is an acceptable "workaround" for starting RDP sessions (the 💻 Icon should by default appear right next to the search bar in KeePass). At least this is a bit quicker to access than going through the context menu.

**Comment by massimobalestra** [comment]
Yes, the 💻 Icon works perfectly and it is what I am using now.
Thank you very much for the good work.

**Comment by massimobalestra** [comment]
Thank you
