### ISSUE TITLE
rdp host evaluation does not work with references in URL 

### ISSUE THREAD

**Issue by Jarous74** [iSnackyCracky/KeePassRDP#25]
**Describe the bug**
When an URL is defined with help of reference (i.e. rdp://{S:host}:3389) then the same string appears in RDP login.
If I just doubleclick on this referenced URL and woiuld paste into text editor I got correct url with evaluated reference (rdp://myhostname:3389)

**To Reproduce**
1. Go to KP entry, 'Advanced' tab
2. Define new custom field "host' and put your hostname there
3. In URL define your URL with a reference (rdp://{S:host}:3389)
4. Save
5. Double click on the URL and paste into text editor - you should see your evaluated reference
6. Use your plugin with Ctrl+M to see incorrect host address in mstsc.exe login screen

**Expected behavior**
mstsc shoud receive hostname already evaluated via the reference

**Screenshots**
![image](https://user-images.githubusercontent.com/97226123/148369674-a805f535-ad48-4a26-b08a-066fa76515fe.png)
![image](https://user-images.githubusercontent.com/97226123/148369731-b2631ebb-b438-403b-995e-ba60e124d1d9.png)

**Additional context**

**Comment by iSnackyCracky** [comment]
Hey @Jarous74,
thanks for your bug report!

References to custom fields of the same entry actually don't work for user name or password fields either at the moment. This is due to how the KeePass SprEngine works and how entries are handled before passing them to mstsc.exe.
(References to other entries - i.e. {REF:A@<UUIDofAnotherEntry>} - should work just fine though, even in the URL field.

However, this is already fixed in an upcoming release in which the whole internal credential selecting and handling process is reworked to allow more flexibility in the future.
