### ISSUE TITLE
Reference fields are not handled correctly

### ISSUE THREAD

**Issue by ahoytguy** [iSnackyCracky/KeePassRDP#4]
When you create an entry for use with RDP and at the bottom left of the page use "Tools" in the edit entry screen and choose to "Insert Field Reference" and then choose "In Password Field" you can select an entry with the credentials you wish to store for this RDP account.  The reference looks something like {REF:P@I:CCD6E5F09E83C84E88B0C3FD9616XXXX}.  When you later choose to use KeePassRDP to open an RDP session with referenced credentials, it uses the actual text of the reference and not the referenced password.  The same is true about the username field if you attempt to reference another entry's username.
Fixing this would make things much simpler for me as I store my windows credentials in one entry and would like to be able to use those to open dozens of RDP entries with that same windows account.  It also allows me to store my RDP entries in organized folders (Main Cluster, DR Cluster, File Servers, DB Servers...) while allowing all to reference a single entry with my windows credentials.
I have attached a few snips to help explain.
![Snag_539c6b](https://user-images.githubusercontent.com/57960169/69173116-1ed3ec80-0acd-11ea-8f92-d0ea0b314e87.png)
![Snag_53dc62](https://user-images.githubusercontent.com/57960169/69173135-25fafa80-0acd-11ea-9591-5c120e681cac.png)
![Snag_53f345](https://user-images.githubusercontent.com/57960169/69173142-28f5eb00-0acd-11ea-8be1-3d5e67a627ef.png)

**Comment by iSnackyCracky** [comment]
Hi @ahoytguy ,

I understand what you mean here and will definitely look into this, so that references get resolved correctly.

The second thing (or "reason" behind that issue - storing credentials only once):
That's already implemented in another way: If you put your rdp-related (i.e. containing the server's URL) in a subfolder named "RDP" and then connect to one of them, you get a selection with all your accounts (as long as they are named "correctly" - see the [readme](https://github.com/iSnackyCracky/KeePassRDP/blob/master/README.md#rdp-subgroup--folder) for details).
As I said, this currently works for entries directly inside a Group/Folder named "RDP". I'll probably implement a change, so that this also works for entries in sub- (or sub-sub-sub-...) folders of "RDP".

I'll keep you updated on both of these.

**Comment by ahoytguy** [comment]
Thank you.
Its a great product. I also appreciate the recent development work you have
been doing.

Aaron

**Comment by iSnackyCracky** [comment]
Hi @ahoytguy,

I've implemented some changes to the method that handles the credentials so as far as I could test in my setup, references should get resolved correctly with the new version ([release v1.8.0](https://github.com/iSnackyCracky/KeePassRDP/releases/tag/v1.8.0))

Please let me know, if you find any issues with that version.

Thank you for helping to improve this Plugin!

**Comment by ahoytguy** [comment]
Thank you, I can confirm with a couple fist pumps today that it does work.
That was incredibly helpful. I have between 75 and 100 servers to manage at
my location (mostly virtual) and this is an invaluable tool to use with
KeePass. I can now change credentials in one place for all servers. I can't
thank you enough.

Aaron
