### ISSUE TITLE
No Connection 

### ISSUE THREAD

**Issue by Mygaloux** [iSnackyCracky/KeePassRDP#7]
Hi,
When i click on the first option "open RDP connection" nothing was happened.
But when i use the option "Open RDP connection without credential" the connection is OK.

My system : Windows 7 Pro X64
Keepass version : 2.43
![2020-01-16_09h31_57](https://user-images.githubusercontent.com/44296623/72506882-1b49b100-3843-11ea-8e75-cef3b3528341.png)

Plugg-in version : 1.10.1.200
![2020-01-16_09h34_48](https://user-images.githubusercontent.com/44296623/72507075-7b405780-3843-11ea-905a-227f13082e72.png)

Best regards.

**Comment by iSnackyCracky** [comment]
Hi @Mygaloux,

this behavior seems kind of weird, because the code that handles the connection is exactly the same (the "without credentials" just disables a part of the code for saving the credentials)...
I assume you did not get any error messages or notifications?
Can you try connecting via the new 💻 button in the toolbar right next to the search box and see what happens?
![image](https://user-images.githubusercontent.com/20481463/72564650-91383180-38b0-11ea-81c2-b90fae474a83.png)

Maybe you can also give a few details of the entry you are trying to connect to:
Are you using field references?
Are you in a RDP subfolder, where the credential picker should appear?
Or, if not, does the entry even contain corresponding credentials? (connection should work without them anyways though)

**Comment by Mygaloux** [comment]
Hi iSnackyCracky,
I try to use the new button in the toolbar right to the search box. I have the same behaviour that the context menu => nothing

See some pictures form my configuration.

![2020-01-17_09h38_14](https://user-images.githubusercontent.com/44296623/72597371-ee160500-390d-11ea-9cf1-b59cfe0ee924.png)

![2020-01-17_09h45_00](https://user-images.githubusercontent.com/44296623/72597471-27e70b80-390e-11ea-86fa-96287924b7f9.png)

![2020-01-17_09h42_02](https://user-images.githubusercontent.com/44296623/72597480-2e758300-390e-11ea-84ec-0aaac453c937.png)

It's possible to have a dev version with log?
I have VS 2019, i can build the project and activate log ?

**Comment by iSnackyCracky** [comment]
Hey @Mygaloux,
I think I found the issue...
The plugin behavior is different in an RDP folder, since the plugin then ignores the credentials in the selected entry and instead searches the parent folder recursively for entries matching combinations of these prefixes: `domain, domänen, local, lokaler, windows` and these postfixes: `admin, user, administrator, benutzer, nutzer`
Therefore you actually don't have to put credentials in every rdp/server entry, but instead can save them once into a single (or multiple) "admin" entry/entries and choose between them interactively.
If no matching entry is found, the code thinks something went wrong and just aborts without any notification.

I'm working on the options menu to customize the RegEx for matching anyways, so I think this will be adressed in the next patch (probably next week)

> It's possible to have a dev version with log?
> I have VS 2019, i can build the project and activate log ?

There is currently no logging functionality implemented, and I probably won't implement one in the future, because the plugin handles security-relevant data, and I don't want to handle that data any more than needed.
You can of course build the project yourself and attach your VS debugger to the KeePass.exe process, set a breakpoint and single-step through to see what happens.

**Comment by Mygaloux** [comment]
Thanks a lot for your feedback.

**Comment by Mygaloux** [comment]
Hi,
I solve my issue.
I rename the group "RDP" on "Connexion à distance" and now it works like expected.
